### PR TITLE
Error rather than stack overflow if using template in non-html namespace

### LINKED ISSUE #472: Max call stack size exceeded when template within SVG element
**I'm submitting a bug report**

aurelia-templating@1.1.0

Windows 10
Node v6.6.0
NPM v3.10.3
JSPM v0.16.45

**Browsers**
- Chrome 53.0.2785.116
- nwjs 0.17.3-sdk

**Language:**
TypeScript

**Current behavior:**

```
aurelia-logging-console.js:54 ERROR [app-router] RangeError: Maximum call stack size exceeded
    at ViewResources._invokeHook (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:1276:63)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2531:17)
    at ViewCompiler._compileElement (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2732:28)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2565:23)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2534:12)
    at ViewCompiler._compileElement (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2732:28)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2565:23)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2534:12)
    at ViewCompiler._compileElement (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2732:28)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2565:23)
```

`graph.html`

``` html
<template>
  <svg width="800" height="400" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
    <template replaceable part="contents">

    </template>
  </svg>
</template>
```

`graph.ts`

``` typescript
export class Graph {
}
```

`index.html`

``` html
<template>
  <require from="./graph"></require>

  <graph>
    <template replace-part="contents">
       <!--  I'm going to add my custom svg elements in here eventually -->
    </template>
  </graph>
</template>
```

If I comment out `<template replaceable part="contents"></template>` from within the `svg` element I no longer get the crash. Sometimes in chrome I'll even get "Aw, Snap!" and when I run in nwjs it normally takes down the whole app.

### PR DESCRIPTION
**Pull request by timfish**
Closes #472

### CODE REVIEW

File: src/view-compiler.js [hunk 1]
```diff
@@ -306,6 +306,9 @@ export class ViewCompiler {
       }
       return node.nextSibling;
     } else if (tagName === 'template') {
+      if(!node.content){
```
Comment (stsje) [inline src/view-compiler.js]: On MDN they test using `if ('content' in document.createElement('template')) {`, so maybe it would be preferred to have the condition be `if (!('content' in node)) {`
Then it wouldn't begin to check the value of `content`

**Comment by jdanyow** [comment]
@timfish thanks for the PR! Could you please include a unit test covering this change? This way we'll know what the change fixes and we won't regress on the fix when making future changes.

**Comment by timfish** [comment]
I've added a test, but it doesn't fail if I remove my check!

**Comment by timfish** [comment]
Well, the test doesn't fail, but the Chrome karma instance stack overflows as that was the behaviour before. Is that suitable?

**Comment by EisenbergEffect** [comment]
@timfish Can you share a code sample that would trigger this error?

**Comment by timfish** [comment]
As per #472, any `<template>` within an `<svg>` caused a stackoverflow but with this change should throw a helpful exception instead.
